[package]
name = "actix-session"
version = "0.5.0-beta.5"
authors = ["Nikolay Kim <fafhrd91@gmail.com>", "Luca Palmieri <rust@lpalmieri.com>"]
description = "Sessions for Actix web"
keywords = ["http", "web", "framework", "async", "session"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-extras.git"
license = "MIT OR Apache-2.0"
edition = "2018"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "actix_session"
path = "src/lib.rs"

[features]
default = []
cookie-session = []
redis-actor-session = ["actix-redis", "actix", "futures-core"]
redis-rs-session = ["redis", "futures-core"]

[dependencies]
actix-service = "2.0.0"
actix-utils = "3"
actix-web = { version = "4.0.0-beta.14", default_features = false, features = ["cookies", "secure-cookies"] }

async-trait = "0.1"
derive_more = "0.99.5"
futures-util = { version = "0.3.7", default-features = false }
log = "0.4"
time = "0.2.23"
serde = { version = "1.0.101" }
serde_json = { version = "1.0.40" }
rand = { version = "0.8.0" }
tracing = { version = "0.1.29", default-features = false }
thiserror = "1.0.30"
anyhow = "1.0.51"

# redis-actor-session
actix-redis = { version = "0.10.0-beta.3", path = "../actix-redis", optional = true}
actix = { version = "0.12.0", default-features = false, optional = true }
futures-core = { version = "0.3.7", default-features = false, optional = true }

# redis-rs-session
redis = { version = "0.21.4", default-features = false, features = ["aio", "tokio-comp", "connection-manager"], optional = true }

[dev-dependencies]
actix-session = { path = ".", features = ["cookie-session", "redis-actor-session", "redis-rs-session"] }
actix-rt = "2"
actix-test = "0.1.0-beta.5"
env_logger = "0.8"

[[example]]
name = "basic"
required-features = ["redis-actor-session"]

[[example]]
name = "authentication"
required-features = ["redis-actor-session"]
