[package]
name = "actix-session"
version = "0.5.0-beta.4"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Sessions for Actix web"
keywords = ["http", "web", "framework", "async", "session"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-extras"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
name = "actix_session"
path = "src/lib.rs"

[features]
default = ["cookie-session"]
cookie-session = ["actix-web/secure-cookies", "serde", "serde_json",]
redis-actor-session = ["actix-redis", "rand", "serde", "serde_json", "cookie-session", "actix", "futures-core"]

[dependencies]
actix-web = { version = "4.0.0-beta.10", default_features = false, features = ["cookies"] }
actix-service = "2.0.0"

derive_more = "0.99.5"
futures-util = { version = "0.3.7", default-features = false }
log = "0.4"
time = "0.2.23"

# redis-actor-session
actix-redis = { version = "0.10.0-beta.3", path = "../actix-redis", optional = true}
rand = { version = "0.8.0", optional = true }
serde = { version = "1.0.101", optional = true }
serde_json = { version = "1.0.40", optional = true }
actix = { version = "0.12.0", default-features = false, optional = true }
futures-core = { version = "0.3.7", default-features = false, optional = true }

[dev-dependencies]
actix-rt = "2"
actix-test = "0.1.0-beta.5"
env_logger = "0.8"

[[example]]
name = "basic"
required-features = ["redis-actor-session"]

[[example]]
name = "authentication"
required-features = ["redis-actor-session"]
